# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: russjt/php-dummy-image-prod

    working_directory: /var/www/html/

    steps:
      - run:
          name: Run PHPUnit Tests
          command: |
            ./vendor/bin/phpunit .
