# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build: 
    docker: 
      - image: blahblah
  test:
    docker:
      - image: russjt/php-dummy-image-prod

    working_directory: /var/www/html/

    steps:
      - run:
          name: Run PHPUnit Tests
          command: |
            mkdir test-results
            ./vendor/bin/phpunit ./test/ --log-junit test-results/result.xml
      - store_artifacts:
          path: test-results/
          destination: test-results
      - store_test_results:
          path: test-results/

workflows:
  version: 2
  build-test:
    jobs:
      - test