apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jimbo-dummy-php-app
  namespace: default
  labels:
    app: jimbo-dummy-php-app
  annotations:
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jimbo-dummy-php-app
    spec:
      containers:
        - name: app
          image: jgedarovich/php-dummy:31
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
