apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dummy-php-app
  namespace: default
  labels:
    app: dummy-php-app
  annotations:
    repo: https://github.com/russtaylor/php-demo-project
    owner: 'russt@etsy.com, #tdi'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dummy-php-app
    spec:
      containers:
        - name: app
          image: gcr.io/etsy-gke-sandbox/php-ci-prod-jimbo
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
